# Generated by Django 5.2 on 2025-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallTables',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('seats', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
