# Generated by Django 5.2 on 2025-06-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halltables',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
