# Generated by Django 5.2 on 2025-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_halltables_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='halltables',
            name='current_session',
            field=models.IntegerField(default=0),
        ),
    ]
