# Generated by Django 5.2 on 2025-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
